### ISSUE TITLE
如何进行实时处理呢？

### ISSUE THREAD

**Issue by panhu** [jagger2048/WebRtc_noise_suppression#4]
我想请问下，如果不使用文件输入数据，而是实时进行处理的话应该如何修改，因为它会保留之前帧的信息，我在实时处理时的效果始终不对。

**Comment by jagger2048** [comment]
Hi,
  实时处理的话， 送入一帧一帧的时域数据即可，也就是 ADC 采集回来的麦克风数据。我们使用文件输入数据是为了离线处理，文件中保存的其实也是时域数据。

**Comment by panhu** [comment]
感谢您的回复，我想请问有没有哪种重采样方法，可以实现自定义长度的上下采样呢？比如我的输入为长160，输出想为256长度或者输出为256，下采样到160，保证比较好的效果，应该怎么做呢？非常感谢

**Comment by jagger2048** [comment]
可以参考
https://ww2.mathworks.cn/help/dsp/ug/fractional-delay-filters-using-farrow-structures.html
中的实现，来进行任意采样率的转换

**Comment by panhu** [comment]
感谢，我把nsprocess做了下修改，让它能够做实时处理，但是好像处理处理的语音在人说话的时候总是会伴随点杂音，而直接使用文件处理的效果没有杂音，不知道是什么问题？以下是我修改的地方，其他没有修改：

void initialize() {
  static int initialized = 0;  // 静态局部变量，用于记录初始化状态

  if (!initialized) {
	NsHandles[0] = WebRtcNs_Create();  
    printf("Initialization\n");
    // 执行初始化操作...
    WebRtcNs_Init(NsHandles[0], 16000);
	WebRtcNs_set_policy(NsHandles[0], kHigh);
    initialized = 1;  // 将初始化状态标记为已完成
  }else {
  	return;
  }
}

int nsProcess(int16_t *buffer, uint32_t sampleRate, uint32_t channels, enum nsLevel level) {
    if (buffer == nullptr) return -1;
   // if (samplesCount == 0) return -1;
    size_t samples = 160; //MIN(480, sampleRate / 100);//480;//MIN(480, sampleRate / 100);
    if (samples == 0) return -1;
    uint32_t num_bands = 1;
    int16_t *input = buffer;
    size_t frames = 1;//(samplesCount / (samples * channels));
   
    initialize();
    for (int i = 0; i < frames; i++) {
        for (int c = 0; c < channels; c++) {
            for (int k = 0; k < samples; k++){
                frameBuffer[k] = input[k * channels + c];
                // printf("%d ",frameBuffer[k]);
            }		
            int16_t *nsIn[1] = {frameBuffer};   //ns input[band][data]

            int16_t *nsOut[1] = {frameBuffer};  //ns output[band][data]
            WebRtcNs_Analyze(NsHandles[c], nsIn[0]);

            WebRtcNs_Process(NsHandles[c], (const int16_t *const *) nsIn, num_bands, nsOut);

            for (int k = 0; k < samples; k++){
                input[k * channels + c] = frameBuffer[k];
            }
        }
    }
    return 1;
}

**Comment by panhu** [comment]
唯一区别就是一个是一帧处理完再调用处理下一帧，一个是一次性处理。但是不知道是不是有什么参数没更新还是哪里处理不对，处理完后人声伴随点杂音
